[project]
name = "pawsupport"
version = "0.1.1"
description = "utils"
authors = [
    { name = "paw", email = "paw@pawrequest.com" }
]

dependencies = [
    'loguru',
    'aiohttp',
]
readme = "README.md"
requires-python = ">= 3.12"

[project.optional-dependencies]
fastui = [
    "fastui",
]
bs4 = [
    "beautifulsoup4",
]
sqlmodel = [
    "sqlmodel>=0.0.14",
]
doc = [
    "docxtpl",
    "pywin32",
    "openpyxl",
    "docx2pdf",
    "pysimplegui",
    "comtypes",
]
sphynx = [
    "sphinx",
]
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    'pytest',
    'pytest-asyncio',
]

[tool.hatch.metadata]
allow-direct-references = true

