[project]
name = "pawsupport"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "paw", email = "paw@pawrequest.com" }
]

# todo optional
dependencies = [
    'loguru',
    "sqlmodel>=0.0.14",
]
readme = "README.md"
requires-python = ">= 3.12"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    'pytest',
    'pytest-asyncio',
]

[tool.hatch.metadata]
allow-direct-references = true
