[project]
name = "pawsupport"
version = "0.1.1"
description = "utils"
authors = [
    { name = "paw", email = "paw@pawrequest.com" }
]

dependencies = [
    'loguru',
    'aiohttp',
]
readme = "README.md"
requires-python = ">= 3.12"

[project.optional-dependencies]
fastui = [
    "fastui",
    "fastapi",
]
bs4 = [
    "beautifulsoup4",
]
sqlmodel = [
    "sqlmodel",
]
office = [
    "docxtpl",
    "pywin32; sys_platform == 'win32'",
    "openpyxl",
    "docx2pdf",
    "pysimplegui",
    "comtypes",
]
docs = [
    "sphinx",
    "sphinx-autodoc-typehints",
    "sphinx-rtd-theme",
    "sphinx-readme",
]
all = ["pawsupport[fastui, bs4, sqlmodel, docs, dev]"]
#all = ["pawsupport[fastui, bs4, sqlmodel, office, docs]"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    'pytest',
    'pytest-asyncio',
]

[tool.hatch.metadata]
allow-direct-references = true

